name: CI
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker build and push
        run: |
          set -euxo pipefail
          IMAGE_REPO=emnoorreef/test-docker-dct
          IMAGE_TAG=$(date +%s)
          IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
          DELEGATION_KEY_FILE="$HOME/.docker/trust/private/${{ secrets.DOCKERHUB_DELEGATED_KEY_ID }}.key"
          export DOCKER_CONTENT_TRUST=1

          echo "Delecation key will be saved at $DELEGATION_KEY_FILE"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          mkdir -p $(dirname "$DELEGATION_KEY_FILE")
          cat <<< "${{ secrets.DOCKERHUB_DELEGATED_KEY }}" > "$DELEGATION_KEY_FILE"
          chmod 600 "$DELEGATION_KEY_FILE"

          docker trust inspect --pretty "$IMAGE_REPO" || true
          docker build -t "$IMAGE_NAME" .
          echo "${{ secrets.DOCKERHUB_DELEGATED_KEY_PASSPHRASE  }}" | docker push "$IMAGE_NAME"
